/**
 * This code was generated by Builder.io.
 */
import React from 'react'

const HideDashboardButton: React.FC = () => {
  return (
    <button className='flex justify-between items-center py-2 pr-2 pl-3 mt-1 w-full text-sm font-semibold leading-6 rounded-xl text-neutral-500'>
      <div className='flex flex-1 shrink justify-between items-center self-stretch my-auto w-full basis-0'>
        <div className='flex flex-1 shrink gap-3 items-center self-stretch my-auto w-full basis-0'>
          <img
            loading='lazy'
            src='https://cdn.builder.io/api/v1/image/assets/TEMP/4c4ed81d0a71292373e1c1fb54fdf0e6df95dda38da4a1cd8daef803955c644f?placeholderIfAbsent=true&apiKey=14a3acb538e54360af1cf1ee025c61c0'
            alt=''
            className='object-contain shrink-0 self-stretch my-auto w-6 aspect-square'
          />
          <div className='self-stretch my-auto'>Ẩn bảng điều khiển</div>
        </div>
      </div>
    </button>
  )
}

export default HideDashboardButton
