/**
 * This code was generated by Builder.io.
 */
import React from 'react'

interface SidebarHeaderProps {
  logo: string
  title: string
}

const SidebarHeader: React.FC<SidebarHeaderProps> = ({ logo, title }) => {
  return (
    <div className='flex overflow-hidden gap-2.5 py-2 w-full text-base leading-none text-gray-900'>
      <img
        loading='lazy'
        src={logo}
        alt='Student Care System Logo'
        className='object-contain shrink-0 w-10 aspect-[1.67]'
      />
      <div className='grow shrink my-auto w-[201px]'>{title}</div>
    </div>
  )
}

export default SidebarHeader
