/**
 * This code was generated by Builder.io.
 */
import React from 'react'

interface SidebarItemProps {
  icon: string
  text: string
  active?: boolean
}

const SidebarItem: React.FC<SidebarItemProps> = ({ icon, text, active }) => {
  const baseClasses = 'flex justify-between items-center py-2 pr-2 pl-3 w-full rounded-xl'
  const activeClasses = active ? 'text-blue-700 bg-sky-50' : ''

  return (
    <div className={`${baseClasses} ${activeClasses} ${active ? 'relative' : ''} mt-1`}>
      <div className='flex flex-1 shrink justify-between items-center self-stretch my-auto w-full basis-0'>
        <div className='flex flex-1 shrink gap-3 items-center self-stretch my-auto w-full basis-0'>
          <img
            loading='lazy'
            src={icon}
            alt=''
            className='object-contain shrink-0 self-stretch my-auto w-6 aspect-square'
          />
          <div className='self-stretch my-auto'>{text}</div>
        </div>
      </div>
      {active && (
        <div className='flex absolute -left-4 top-2/4 z-0 shrink-0 self-start w-1 h-8 bg-blue-600 rounded-none -translate-y-2/4 translate-x-[0%]' />
      )}
    </div>
  )
}

export default SidebarItem
