/**
 * This code was generated by Builder.io.
 */
import React from 'react'
import SidebarItem from './SidebarItem'

interface SidebarSectionProps {
  title: string
  items: Array<{
    icon: string
    text: string
    active?: boolean
  }>
}

const SidebarSection: React.FC<SidebarSectionProps> = ({ title, items }) => {
  return (
    <div className='flex flex-col mt-6 w-full'>
      <div className='gap-2.5 px-3 w-full text-xs leading-none text-zinc-500'>{title}</div>
      <div className='flex flex-col mt-3 w-full text-sm leading-6 text-neutral-500'>
        {items.map((item, index) => (
          <SidebarItem key={index} icon={item.icon} text={item.text} active={item.active} />
        ))}
      </div>
    </div>
  )
}

export default SidebarSection
